version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: test-data-storage-db
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: test_data_storage
    logging:
      options:
        max-file: "5"
        max-size: "10m"


  test-data-service:
    image: auto1/test-data-storage-service:latest
    container_name: test-data-service-api
    expose:
      - 8085
    ports:
      - 8085:8085
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_data_storage
      SPRING_DATASOURCE_USERNAME: db_user
      SPRING_DATASOURCE_PASSWORD: db_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BASIC_USERNAME: basic_auth_user
      BASIC_PASSWORD: basic_auth_password
    logging:
      options:
        max-file: "5"
        max-size: "10m"

  ui:
    image: auto1/test-data-storage-ui:latest
    container_name: test-data-service-ui
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BASE_URL_API: http://localhost:8085
      REACT_APP_BASIC_AUTH_USER: basic_auth_user
      REACT_APP_BASIC_AUTH_PASSWORD: basic_auth_password
    depends_on:
      - test-data-service

volumes:
  db_data: