name: Build Test data storage Docker Image

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile and Create Maven Package
        run: mvn -B package --file pom.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-data-storage
#          path: ${{ github.workspace }}/api-gateway/target/*.jar ??
#          retention-days: 1 ??

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: target/

      - name: Docker build services
        run: |
          docker build . -t auto1/test-data-storage-service:latest -f test-data-storage/Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: |
          docker push auto1/test-data-storage-service:latest
