name: PR check test-data-storage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PR check for test-data-storage
        run: mvn --no-transfer-progress clean -U test
